#########################################################################
## SageApple — BASIC test (Milestone 8)
##
## Run:  sage tests/basic/test_basic.sage   (from the repo root)
#########################################################################

import basic.basic

var failures = 0
var passes = 0
proc check(cond, msg):
    if cond:
        passes = passes + 1
        print("  PASS:", msg)
    else:
        failures = failures + 1
        print("  FAIL:", msg)

proc contains(hay, needle):
    let hn = len(hay)
    let nn = len(needle)
    if nn == 0: return true
    if nn > hn: return false
    var i = 0
    while i <= hn - nn:
        if slice(hay, i, i + nn) == needle:
            return true
        i = i + 1
    return false

proc not_contains(hay, needle):
    if contains(hay, needle):
        return false
    return true

var b = basic.Basic()

print("== immediate ==")
b.input_line("PRINT 1+2")
check(contains(b.out, "3\r\n"), "PRINT 1+2 shows 3")
b.reset_out()
b.input_line("PRINT (3+4)*2")
check(contains(b.out, "14\r\n"), "parenthesised arithmetic")
b.reset_out()
b.input_line("PRINT 10/3")
check(contains(b.out, "3.33333333\r\n"), "integer division yields floats")
b.reset_out()
b.input_line("10 LET A=5")
b.input_line("20 PRINT A*2")
b.input_line("RUN")
check(contains(b.out, "10\r\n"), "LET + variable PRINT")
b.reset_out()

print("== PRINT strings/numbers/negatives ==")
b.new()
b.input_line("10 PRINT \"HELLO\"")
b.input_line("20 LET A = -7")
b.input_line("30 PRINT A")
b.input_line("RUN")
check(contains(b.out, "HELLO"), "PRINT string literal")
check(contains(b.out, "-7"), "PRINT negative number")

print("== GOTO / IF-THEN loop ==")
b.new()
b.input_line("10 LET I=1")
b.input_line("20 PRINT I")
b.input_line("30 LET I=I+1")
b.input_line("40 IF I<4 GOTO 20")
b.input_line("50 PRINT \"DONE\"")
b.input_line("RUN")
check(contains(b.out, "1\r\n2\r\n3\r\n"), "loop body printed")
check(contains(b.out, "DONE"), "loop exits to statement")

print("== IF/THEN with equality ==")
b.new()
b.input_line("10 LET Q=7")
b.input_line("20 IF Q=7 THEN PRINT \"YES\"")
b.input_line("30 IF Q=8 THEN PRINT \"NOPE\"")
b.input_line("RUN")
check(contains(b.out, "YES"), "IF-THEN true branch")
check(not_contains(b.out, "NOPE"), "IF-THEN false branch")

print("== FOR/NEXT ==")
b.new()
b.input_line("10 FOR I=1 TO 3")
b.input_line("20 PRINT I")
b.input_line("30 NEXT I")
b.input_line("40 PRINT \"END\"")
b.input_line("RUN")
check(contains(b.out, "1\r\n2\r\n3\r\n"), "FOR loop counts up")
check(contains(b.out, "END"), "program continues after NEXT")

print("== FOR/NEXT with STEP ==")
b.new()
b.input_line("10 FOR I=5 TO 1 STEP -1")
b.input_line("20 PRINT I")
b.input_line("30 NEXT I")
b.input_line("RUN")
check(contains(b.out, "5\r\n4\r\n3\r\n2\r\n1\r\n"), "STEP -1 counts down")

print("== INPUT ==")
b.new()
b.input_line("10 INPUT A")
b.input_line("20 PRINT A")
b.input_line("RUN")
check(contains(b.out, "?\r\n") or contains(b.out, "?"), "INPUT prints the ? prompt")
b.reset_out()
push(b.inq, "42")
b.new()
b.input_line("10 INPUT A")
b.input_line("20 PRINT A")
b.input_line("RUN")
check(contains(b.out, "42\r\n"), "INPUT reads queued value")

print("== LIST/NEW ==")
b.new()
b.input_line("10 PRINT 1")
b.input_line("20 PRINT 2")
b.input_line("LIST")
check(contains(b.out, "10 PRINT 1"), "LIST shows line 10")
b.input_line("NEW")
b.reset_out()
b.input_line("LIST")
check(not_contains(b.out, "10"), "NEW clears program")

print("== Applesoft expressions ==")
b.new()
b.input_line("PRINT 1.5+1")
check(contains(b.out, "2.5\r\n"), "float addition")
b.reset_out()
b.input_line("PRINT 2^10")
check(contains(b.out, "1024\r\n"), "power")
b.reset_out()
b.input_line("PRINT -2^2")
check(contains(b.out, "-4\r\n"), "unary minus binds loose")
b.reset_out()
b.input_line("PRINT 2^-2")
check(contains(b.out, "0.25\r\n"), "negative power")
b.reset_out()
b.input_line("PRINT 0.001")
check(contains(b.out, "1E-03\r\n"), "scientific format small")
b.reset_out()
b.input_line("PRINT 1E9")
check(contains(b.out, "1E+09\r\n"), "scientific input")
b.reset_out()
b.input_line("PRINT INT(-3.9)")
check(contains(b.out, "-4\r\n"), "INT floors")
b.reset_out()
b.input_line("PRINT SQR(16)")
check(contains(b.out, "4\r\n"), "SQR")
b.reset_out()
b.input_line("PRINT LEN(\"HELLO\")")
check(contains(b.out, "5\r\n"), "LEN")
b.reset_out()
b.input_line("PRINT MID$(\"HELLO\",2,3)")
check(contains(b.out, "ELL\r\n"), "MID$")
b.reset_out()
b.input_line("PRINT \"A\"+\"B\"")
check(contains(b.out, "AB\r\n"), "string concat")
b.reset_out()
b.input_line("PRINT 5+")
check(contains(b.out, "SYNTAX ERROR"), "trailing operator errors")
b.reset_out()
b.input_line("PRINT 7 MOD 3")
check(contains(b.out, "SYNTAX ERROR"), "MOD is not an operator")
b.reset_out()
b.input_line("PRINT 1/0")
check(contains(b.out, "DIVISION BY ZERO"), "division by zero")
b.reset_out()

print("== Applesoft control flow ==")
b.new()
b.input_line("10 GOSUB 100")
b.input_line("20 PRINT \"BACK\"")
b.input_line("30 END")
b.input_line("100 PRINT \"SUB\"")
b.input_line("110 RETURN")
b.input_line("RUN")
check(contains(b.out, "SUB\r\nBACK\r\n"), "GOSUB/RETURN")
b.reset_out()
b.new()
b.input_line("10 FOR I=1 TO 3: PRINT I;: NEXT I")
b.input_line("RUN")
check(contains(b.out, "123"), "colon-separated statements")
b.reset_out()
b.new()
b.input_line("10 A(2)=7")
b.input_line("20 PRINT A(2)")
b.input_line("RUN")
check(contains(b.out, "7\r\n"), "array assign and read")
b.reset_out()
b.new()
b.input_line("10 DEF FN S(X)=X*X")
b.input_line("20 PRINT FN S(5)")
b.input_line("RUN")
check(contains(b.out, "25\r\n"), "DEF FN")
b.reset_out()
b.new()
b.input_line("10 DATA 1,2,3")
b.input_line("20 READ A,B,C")
b.input_line("30 PRINT A+B+C")
b.input_line("RUN")
check(contains(b.out, "6\r\n"), "DATA/READ")
b.reset_out()

print("== Applesoft errors ==")
b.new()
b.input_line("10 PRINT A")
b.input_line("20 GOTO 999")
b.input_line("RUN")
check(contains(b.out, "UNDEF'D STATEMENT ERROR IN 20"), "GOTO missing line")
b.reset_out()
b.new()
b.input_line("10 NEXT I")
b.input_line("RUN")
check(contains(b.out, "NEXT WITHOUT FOR ERROR IN 10"), "NEXT WITHOUT FOR")
b.reset_out()
b.new()
b.input_line("10 PRINT \"A\"-1")
b.input_line("RUN")
check(contains(b.out, "TYPE MISMATCH ERROR IN 10"), "string minus number")
b.reset_out()
b.new()
b.input_line("5 ONERR GOTO 100")
b.input_line("10 PRINT 1/0")
b.input_line("20 END")
b.input_line("100 PRINT \"CAUGHT\"")
b.reset_out()
b.input_line("RUN")
check(contains(b.out, "CAUGHT"), "ONERR GOTO traps errors")
b.reset_out()

print("== Applesoft functions ==")
b.new()
b.input_line("10 A=65")
b.input_line("20 PRINT CHR$(A)")
b.input_line("30 PRINT ASC(\"A\")")
b.input_line("40 PRINT LEFT$(\"HELLO\",2)")
b.input_line("50 PRINT RIGHT$(\"HELLO\",2)")
b.input_line("60 PRINT STR$(123.5)")
b.input_line("70 PRINT VAL(\"42\")")
b.input_line("80 PRINT SGN(-5)")
b.input_line("90 PRINT ABS(-5)")
b.input_line("100 PRINT LEN(\"ABC\")")
b.input_line("RUN")
check(contains(b.out, "A\r\n"), "CHR$")
check(contains(b.out, "65\r\n"), "ASC")
check(contains(b.out, "HE\r\n"), "LEFT$")
check(contains(b.out, "LO\r\n"), "RIGHT$")
check(contains(b.out, "123.5"), "STR$")
check(contains(b.out, "42\r\n"), "VAL")
check(contains(b.out, "-1\r\n"), "SGN")
check(contains(b.out, "5\r\n"), "ABS")
check(contains(b.out, "3\r\n"), "LEN")
b.reset_out()

print("")
print("Results:", passes, "passed,", failures, "failed")
if failures == 0:
    print("ALL OK")