import compiler.asm6502

proc build():
    let source = [
        "org $D000",
        "; --- boot banner over the serial console ---",
        "start:",
        "    LDA #$41",
        "    STA $C080",
        "    LDA #$32",
        "    STA $C080",
        "    LDA #$0D",
        "    STA $C080",
        "    LDA #$0A",
        "    STA $C080",
        "; --- seed the text page with HI and show it on the console ---",
        "    LDA #$C8",
        "    STA $0400",
        "    LDA #$C9",
        "    STA $0401",
        "    LDA #$48",
        "    STA $C080",
        "    LDA #$49",
        "    STA $C080",
        "    LDA #$0D",
        "    STA $C080",
        "    LDA #$0A",
        "    STA $C080",
        "; --- cursor starts just past HI ---",
        "    LDA #$02",
        "    STA $10",
        "    LDA #$04",
        "    STA $11",
        "    LDA #$00",
        "    STA $13",
        "; --- keyboard loop ---",
        "poll:",
        "    LDA $C010",
        "    BPL poll",
        "    LDA $C000",
        "    AND #$7F",
        "    CMP #$0D",
        "    BEQ newline",
        "    CMP #$0A",
        "    BEQ newline",
        "    CMP #$08",
        "    BEQ backsp",
        "    CMP #$7F",
        "    BEQ backsp",
        "    CMP #$20",
        "    BCC poll",
        "; --- printable: echo, store high-bit char, advance the cursor ---",
        "    STA $C080",
        "    ORA #$80",
        "    STA $12",
        "    LDY #$00",
        "    LDA $12",
        "    STA ($10),Y",
        "    INC $10",
        "    BNE nocarry",
        "    INC $11",
        "nocarry:",
        "    INC $13",
        "    LDA $13",
        "    CMP #$28",
        "    BNE poll",
        "    LDA #$00",
        "    STA $13",
        "    JMP poll",
        "; --- Return / Line Feed: start of the next 40-column row ---",
        "newline:",
        "    LDA #$0D",
        "    STA $C080",
        "    LDA #$0A",
        "    STA $C080",
        "    SEC",
        "    LDA $10",
        "    SBC $13",
        "    STA $10",
        "    LDA $11",
        "    SBC #$00",
        "    STA $11",
        "    CLC",
        "    LDA $10",
        "    ADC #$28",
        "    STA $10",
        "    LDA $11",
        "    ADC #$00",
        "    STA $11",
        "    LDA #$00",
        "    STA $13",
        "    JMP poll",
        "; --- backspace: step back, clear the cell, echo BS SP BS ---",
        "backsp:",
        "    LDA $13",
        "    BEQ bsp_row",
        "    DEC $13",
        "    DEC $10",
        "    BNE bsp_go",
        "    DEC $11",
        "    JMP bsp_go",
        "bsp_row:",
        "    SEC",
        "    LDA $10",
        "    SBC #$28",
        "    STA $10",
        "    LDA $11",
        "    SBC #$00",
        "    STA $11",
        "    LDA #$27",
        "    STA $13",
        "bsp_go:",
        "    LDA #$A0",
        "    LDY #$00",
        "    STA ($10),Y",
        "    LDA #$08",
        "    STA $C080",
        "    LDA #$20",
        "    STA $C080",
        "    LDA #$08",
        "    STA $C080",
        "    JMP poll",
    ]
    let assembled = asm6502.asm(source, 0xD000)
    let code = assembled[0]
    var rom = []
    var i = 0
    while i < 0x3000:
        push(rom, 0x00)
        i = i + 1
    i = 0
    while i < len(code) and i < 0x3000:
        rom[i] = code[i] & 0xFF
        i = i + 1
    rom[0x2FFA] = 0x00
    rom[0x2FFB] = 0xD0
    rom[0x2FFC] = 0x00
    rom[0x2FFD] = 0xD0
    rom[0x2FFE] = 0x00
    rom[0x2FFF] = 0xD0
    return rom
