#########################################################################
## SageApple — AVR ROM generator + host-equivalence reference (M13)
##
##   1. Assembles the monitor at $E000 (8KB window) for the ATmega328P.
##   2. Emits avr/rom.c (const byte array) + avr/host_expected.txt
##      (the UART transcript of the exact host test session, produced
##      by the reference Sage implementation).
##
## Run:  sage tools/rom_gen.sage   (from the repo root)
#########################################################################

import sageapple.monitor
import sageapple.machine


## ---- helpers (must precede first use) --------------------------------
proc h2(v):
    let dig = "0123456789ABCDEF"
    return dig[(v >> 4) & 0xF] + dig[v & 0xF]

proc hex8(v):
    return h2(v)

var img8 = monitor.build_monitor_rom_at(0xE000, 8192, 0xE000)
print("monitor image bytes:", len(img8))

## ---- write avr/rom.c ------------------------------------------------
var w = []
push(w, "/* Auto-generated by tools/rom_gen.sage — 6502 ROM $E000-$FFFF. */")
push(w, "#include <avr/pgmspace.h>")
push(w, "const uint8_t MONROM[8192] PROGMEM = {")
var row = "  "
var n = 0
while n < len(img8):
    if len(row) > 70:
        push(w, row)
        row = "  "
    row = row + "0x" + hex8(img8[n]) + ","
    n = n + 1
push(w, row)
push(w, "};")
import io
var txt = ""
var i = 0
while i < len(w):
    if i > 0:
        txt = txt + "\n"
    txt = txt + w[i]
    i = i + 1
io.writefile("avr/rom.inc", txt + "\n")
print("wrote avr/rom.inc")
var txt2 = ""
txt2 = txt2 + "/* Auto-generated by tools/rom_gen.sage — host build. */\n\n#include <stdint.h>\n"
txt2 = txt2 + "uint8_t MONROM[8192] = {\n"
var r = ""
var nn = 0
while nn < len(img8):
    if len(r) > 70:
        txt2 = txt2 + "  " + r + "\n"
        r = ""
    r = r + "0x" + hex8(img8[nn]) + ","
    nn = nn + 1
if len(r) > 0:
    txt2 = txt2 + "  " + r + "\n"
txt2 = txt2 + "};\n"
io.writefile("avr/rom_host.c", txt2)
print("wrote avr/rom_host.c")

## ---- 32KB image for the host reference machine ---------------------
var img32 = []
var k = 0
while k < 32768:
    push(img32, 0)
    k = k + 1
var m = 0
while m < 8192:
    img32[0x6000 + m] = img8[m]
    m = m + 1
img32[0x7FFC] = 0x00
img32[0x7FFD] = 0xE0

## ---- reference transcript for the host C test -----------------------
let mach = machine.SageApple()
mach.boot_rom(img32)
let uart = mach.bus.uart
let cpu = mach.cpu

var CGUARD = 60000
proc drive(in_bytes):
    uart.receive_str(in_bytes)
    var steps = 0
    while steps < CGUARD:
        cpu.step()
        steps = steps + 1

var transcript = ""
proc command(cmd):
    drive(cmd)
    drive("\r")

drive("")
command("help")
command("regs")
command("peek 0000")
command("poke 0000 42")
command("peek 0000")
command("dump 0030 0030")
command("xyz")
command("run")
command("reset")
command("help")

## the full transcript after the whole session (host app does the same)
transcript = uart.tx_text()
io.writefile("avr/host_expected.txt", transcript)
print("wrote avr/host_expected.txt (" + str(len(transcript)) + " bytes)")